[project]
name = "data-eng"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rmdhnz", email = "ramadhanfadhly2@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.2",
    "numpy>=2.5.3",
    "psycopg[binary]>=3.3.5",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "redis>=8.1.0",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
data-eng = "data_eng:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.6",
]
