"""generate source table

Revision ID: 00b0bec5b3b9
Revises: 
Create Date: 2026-09-10 03:41:13.754467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b0bec5b3b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS source")
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='source'
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_customers_customer_code'), 'customers', ['customer_code'], unique=True, schema='source')
    op.create_index(op.f('ix_source_customers_email'), 'customers', ['email'], unique=True, schema='source')
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['source.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_orders_customer_id'), 'orders', ['customer_id'], unique=False, schema='source')
    op.create_index(op.f('ix_source_orders_order_date'), 'orders', ['order_date'], unique=False, schema='source')
    op.create_index(op.f('ix_source_orders_order_number'), 'orders', ['order_number'], unique=True, schema='source')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['source.categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_products_category_id'), 'products', ['category_id'], unique=False, schema='source')
    op.create_index(op.f('ix_source_products_sku'), 'products', ['sku'], unique=True, schema='source')
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['source.orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['source.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='source')
    op.create_index(op.f('ix_source_order_items_product_id'), 'order_items', ['product_id'], unique=False, schema='source')
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['source.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_payments_order_id'), 'payments', ['order_id'], unique=False, schema='source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_payments_order_id'), table_name='payments', schema='source')
    op.drop_table('payments', schema='source')
    op.drop_index(op.f('ix_source_order_items_product_id'), table_name='order_items', schema='source')
    op.drop_index(op.f('ix_source_order_items_order_id'), table_name='order_items', schema='source')
    op.drop_table('order_items', schema='source')
    op.drop_index(op.f('ix_source_products_sku'), table_name='products', schema='source')
    op.drop_index(op.f('ix_source_products_category_id'), table_name='products', schema='source')
    op.drop_table('products', schema='source')
    op.drop_index(op.f('ix_source_orders_order_number'), table_name='orders', schema='source')
    op.drop_index(op.f('ix_source_orders_order_date'), table_name='orders', schema='source')
    op.drop_index(op.f('ix_source_orders_customer_id'), table_name='orders', schema='source')
    op.drop_table('orders', schema='source')
    op.drop_index(op.f('ix_source_customers_email'), table_name='customers', schema='source')
    op.drop_index(op.f('ix_source_customers_customer_code'), table_name='customers', schema='source')
    op.drop_table('customers', schema='source')
    op.drop_table('categories', schema='source')
    # ### end Alembic commands ###
