"""generate warehouse table

Revision ID: 38bb5e93a71c
Revises: 00b0bec5b3b9
Create Date: 2026-09-10 04:27:32.351304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38bb5e93a71c"
down_revision: Union[str, Sequence[str], None] = "00b0bec5b3b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS warehouse")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "dim_category",
        sa.Column("category_key", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("category_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("category_key"),
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_dim_category_category_id"),
        "dim_category",
        ["category_id"],
        unique=True,
        schema="warehouse",
    )
    op.create_table(
        "dim_customer",
        sa.Column("customer_key", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("customer_key"),
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_dim_customer_customer_code"),
        "dim_customer",
        ["customer_code"],
        unique=False,
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_dim_customer_customer_id"),
        "dim_customer",
        ["customer_id"],
        unique=True,
        schema="warehouse",
    )
    op.create_table(
        "dim_date",
        sa.Column("date_key", sa.Integer(), nullable=False),
        sa.Column("full_date", sa.Date(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("quarter", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("month_name", sa.String(length=20), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("day_name", sa.String(length=20), nullable=False),
        sa.Column("is_weekend", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("date_key"),
        sa.UniqueConstraint("full_date"),
        schema="warehouse",
    )
    op.create_table(
        "dim_product",
        sa.Column("product_key", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("product_name", sa.String(length=150), nullable=False),
        sa.Column("category_key", sa.Integer(), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_key"],
            ["warehouse.dim_category.category_key"],
        ),
        sa.PrimaryKeyConstraint("product_key"),
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_dim_product_category_key"),
        "dim_product",
        ["category_key"],
        unique=False,
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_dim_product_product_id"),
        "dim_product",
        ["product_id"],
        unique=True,
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_dim_product_sku"),
        "dim_product",
        ["sku"],
        unique=False,
        schema="warehouse",
    )
    op.create_table(
        "fact_sales",
        sa.Column("sales_key", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_key", sa.Integer(), nullable=False),
        sa.Column("customer_key", sa.Integer(), nullable=False),
        sa.Column("product_key", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("sales_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_key"],
            ["warehouse.dim_customer.customer_key"],
        ),
        sa.ForeignKeyConstraint(
            ["date_key"],
            ["warehouse.dim_date.date_key"],
        ),
        sa.ForeignKeyConstraint(
            ["product_key"],
            ["warehouse.dim_product.product_key"],
        ),
        sa.PrimaryKeyConstraint("sales_key"),
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_fact_sales_customer_key"),
        "fact_sales",
        ["customer_key"],
        unique=False,
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_fact_sales_date_key"),
        "fact_sales",
        ["date_key"],
        unique=False,
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_fact_sales_order_id"),
        "fact_sales",
        ["order_id"],
        unique=False,
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_fact_sales_order_number"),
        "fact_sales",
        ["order_number"],
        unique=False,
        schema="warehouse",
    )
    op.create_index(
        op.f("ix_warehouse_fact_sales_product_key"),
        "fact_sales",
        ["product_key"],
        unique=False,
        schema="warehouse",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_warehouse_fact_sales_product_key"),
        table_name="fact_sales",
        schema="warehouse",
    )
    op.drop_index(
        op.f("ix_warehouse_fact_sales_order_number"),
        table_name="fact_sales",
        schema="warehouse",
    )
    op.drop_index(
        op.f("ix_warehouse_fact_sales_order_id"),
        table_name="fact_sales",
        schema="warehouse",
    )
    op.drop_index(
        op.f("ix_warehouse_fact_sales_date_key"),
        table_name="fact_sales",
        schema="warehouse",
    )
    op.drop_index(
        op.f("ix_warehouse_fact_sales_customer_key"),
        table_name="fact_sales",
        schema="warehouse",
    )
    op.drop_table("fact_sales", schema="warehouse")
    op.drop_index(
        op.f("ix_warehouse_dim_product_sku"),
        table_name="dim_product",
        schema="warehouse",
    )
    op.drop_index(
        op.f("ix_warehouse_dim_product_product_id"),
        table_name="dim_product",
        schema="warehouse",
    )
    op.drop_index(
        op.f("ix_warehouse_dim_product_category_key"),
        table_name="dim_product",
        schema="warehouse",
    )
    op.drop_table("dim_product", schema="warehouse")
    op.drop_table("dim_date", schema="warehouse")
    op.drop_index(
        op.f("ix_warehouse_dim_customer_customer_id"),
        table_name="dim_customer",
        schema="warehouse",
    )
    op.drop_index(
        op.f("ix_warehouse_dim_customer_customer_code"),
        table_name="dim_customer",
        schema="warehouse",
    )
    op.drop_table("dim_customer", schema="warehouse")
    op.drop_index(
        op.f("ix_warehouse_dim_category_category_id"),
        table_name="dim_category",
        schema="warehouse",
    )
    op.drop_table("dim_category", schema="warehouse")
    # ### end Alembic commands ###
